stages:
  - build
  - pipeline
  - plotting

# image: atlas/analysisbase:latest
# image: atlas/slc6-atlasos:latest
image: atlasadc/atlas-grid-centos7

hhCompile:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SSL_NO_VERIFY: "true"
  script:
    - set +e
    # - source /release_setup.sh
    - shopt -s expand_aliases
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
    - base_path=$(pwd)
    - cd submodules/workspaceCombiner; git status
    - git branch development --track remotes/origin/development
    #- git checkout development
    - git checkout 0db0e09c
    - git apply ../../workspaceCombiner.patch
    - git apply ../../workspaceCombiner.patch2
    - head -n 30 app/manager.cxx
    - cd $base_path
    - cd submodules/RooFitExtensions; git status
    - git checkout 7af33678
    - source compile.sh
    - source setup.sh
  artifacts:
    paths:
      - submodules
      - python_modules
      - scripts
      - setup.sh
#  when: manual

RunPipeline:
  stage: pipeline
  variables:
#    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SSL_NO_VERIFY: "true"
    output_dir: output
    input_dir: input
  before_script:
    - set +e
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - echo "lxplus.cern.ch, ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPZvfRF+9L7TR3FRPyLFdcsXSZ6RQYJHfOjzzWB94sX0gP34Cgij9p4ukL900sVVvw3LPM5OxxFSNIXGztFYu4o=" > ~/.ssh/known_hosts
    - echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo $SERVICE_PASS | kinit -f $CERN_USER || echo something
    - mkdir -p $input_dir
    - scp -r -i ~/.ssh/id_rsa ${CERN_USER}@lxplus.cern.ch:/afs/cern.ch/work/z/zhangr/HHcomb/hh_combination_fw/input/20201007 $input_dir
  script:
    # - source /release_setup.sh
    - shopt -s expand_aliases
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
    - source setup.sh || echo ignore setupATLAS return code
    - which python
    - python scripts/pipeline/processChannels.py $input_dir $output_dir
    - python scripts/combination/auto/combine_ws.py $output_dir
  artifacts:
    paths:
      - $output_dir
  #when: manual

RunPlot:
  stage: plotting
  variables:
#    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SSL_NO_VERIFY: "true"
    input_dir: output
    output_dir: submodules/hh_plot/limit_plots
  script:
    - set +e
    - shopt -s expand_aliases
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
    - mv $input_dir ../
    - cd submodules/hh_plot
    - source setup.sh || echo ignore setupATLAS return code
    - root -l -q -b MakeLimitPlots_nonres_paper.cxx
  artifacts:
    paths:
      - $output_dir
  #when: manual
