stages:
  - build
  - process
  - combine
  - plotting
  - download

image: atlasadc/atlas-grid-centos7

hhCompile:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SSL_NO_VERIFY: "true"
  script:
    - set +e
    - shopt -s expand_aliases
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
    - base_path=$(pwd)
    - cd submodules/workspaceCombiner
    - git apply --whitespace=nowarn ../../workspaceCombiner.patch
    - git status
    - cd $base_path
    - source compile.sh
    - source setup.sh
  artifacts:
    paths:
      - submodules
      - python_modules
      - scripts
      - setup.sh

.IStep1:
  stage: process
  needs:
    - job: hhCompile
  variables:
    GIT_SSL_NO_VERIFY: "true"
    input_dir: input
  before_script:
    - set +e
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - echo "lxplus.cern.ch, ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPZvfRF+9L7TR3FRPyLFdcsXSZ6RQYJHfOjzzWB94sX0gP34Cgij9p4ukL900sVVvw3LPM5OxxFSNIXGztFYu4o=" > ~/.ssh/known_hosts
    - echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo $SERVICE_PASS | kinit -f $CERN_USER || echo something
    - mkdir -p $input_dir/$version
    - scp -r -i ~/.ssh/id_rsa ${CERN_USER}@lxplus.cern.ch:/afs/cern.ch/work/z/zhangr/HHcomb/FullRun2Workspaces/original/$version/CI/* $input_dir/$version/
    - ls $input_dir/$version/*/nonres/0.root
    - shopt -s expand_aliases
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
    - echo $input_dir/$version
    - source setup.sh || echo ignore setupATLAS return code
  artifacts:
    paths:
      - $output_dir

.IStep2:
  stage: combine
  variables:
    GIT_SSL_NO_VERIFY: "true"
    input_dir: output
  before_script:
    - set +e
    - shopt -s expand_aliases
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
    - source setup.sh || echo ignore setupATLAS return code
  artifacts:
    paths:
      - $input_dir

###################################
## Non-resonant Process channels ##
###################################
.NRProcess:
  extends: .IStep1
  variables:
    output_dir: output/NR
    mini_option: minimizer.json
    version: 20211106_proj_all
    other_options: ""
  allow_failure: true
  script:
    - echo HHComb process_channels -i $input_dir/$version -c $channel -r nonres -o $output_dir --minimizer_options configs/$mini_option --config configs/regularization_proj_v11.yaml $other_options
    - HHComb process_channels -i $input_dir/$version -c $channel -r nonres -o $output_dir --minimizer_options configs/$mini_option --config configs/regularization_proj_v11.yaml $other_options

NR_proj_mu_pro:
  extends: .NRProcess
  variables:
    output_dir: output/NR
    channel: bbyy,bbtautau
  only:
    - branches
    - tags

NR_proj_pro_stat:
  extends: .NRProcess
  variables:
    output_dir: output/stat
    mini_option: minimizer_stat.json
    channel: bbyy,bbtautau
  only:
    - tags
    - master
    - CI

KL_proj_pro_yy:
  extends: .NRProcess
  variables:
    output_dir: output/indiv
    channel: bbyy
    other_options: "--file_format <mass[F]>_kl_<kl[P]>"
  only:
    - tags
    - master
    - CI

KL_proj_pro_tt:
  extends: .NRProcess
  variables:
    output_dir: output/indiv
    channel: bbtautau
    other_options: "--file_format <mass[F]>_kl_<kl[P]>"
  only:
    - tags
    - master
    - CI

###################################
## None-resonant combination     ##
###################################
# Default is correlated (bbtautau and bbyy)
.NRCombine_ws:
  extends: .IStep2
  variables:
    mini_option: minimizer.json
    np_option: np_map_nonres_v10.json
    other_options: ""
  allow_failure: true
  script:
    - echo HHComb combine_ws -i $input_dir -c $channels -r nonres --minimizer_options configs/$mini_option $other_options --scheme configs/$np_option
    - HHComb combine_ws -i $input_dir -c $channels -r nonres --minimizer_options configs/$mini_option $other_options --scheme configs/$np_option
  only:
    - tags
    - master
    - CI

# For PUB: mu limit
NR_proj_comb_mu:
  extends: .NRCombine_ws
  needs:
    - job: hhCompile
    - job: NR_proj_mu_pro
  variables:
    input_dir: output/NR
    channels: bbtautau,bbyy

NR_proj_comb_stat:
  extends: .NRCombine_ws
  needs:
    - job: hhCompile
    - job: NR_proj_pro_stat
  variables:
    input_dir: output/stat
    channels: bbtautau,bbyy
    mini_option: minimizer_stat.json

# For PUB: KL xsec
indiv_XSScan:
  extends: .NRCombine_ws
  needs:
    - job: hhCompile
    - job: KL_proj_pro_yy
    - job: KL_proj_pro_tt
  variables:
    input_dir: output/indiv
    channels: bbtautau,bbyy
    np_option: np_map_kl_v10.json
    other_options: "--file_format <mass[F]>_kl_<kl[P]>"


###################################
## parametrised kl workspace     ##
###################################
LHProcess:
  extends: .IStep1
  needs:
    - job: hhCompile
  variables:
    output_dir: output/param
    mini_option: minimizer.json
    version: 20211106_mu
    channel: bbtautau,bbyy
    other_options: "--file_format <mass[F]>_kl --param klambda=1"
    np_option: np_map_kl_v10.json
  allow_failure: true
  script:
    - echo HHComb process_channels -i $input_dir/$version -c $channel -r nonres -o $output_dir --minimizer_options configs/$mini_option --config configs/regularization_kl.yaml --skip-limit --no-cache $other_options
    - HHComb process_channels -i $input_dir/$version -c $channel -r nonres -o $output_dir --minimizer_options configs/$mini_option --config configs/regularization_kl.yaml --skip-limit --no-cache $other_options
    - echo HHComb combine_ws -i $output_dir -r nonres -c $channel --minimizer_options configs/$mini_option --config configs/regularization_kl.yaml --scheme configs/$np_option --skip-limit --no-cache $other_options
    - HHComb combine_ws -i $output_dir -r nonres -c $channel --minimizer_options configs/$mini_option --config configs/regularization_kl.yaml --scheme configs/$np_option --skip-limit --no-cache $other_options


param_LHScan:
  extends: .IStep2
  needs:
    - job: hhCompile
    - job: LHProcess
  variables:
    output_dir: output/param
    other_options: "--min -2 --max 6 --step 1"
    channel: bbtautau,bbyy
  allow_failure: true
  script:
    - echo HHComb kl_likelihood -i $output_dir -c $channel $other_options
    - HHComb kl_likelihood -i $output_dir -c $channel $other_options
  only:
    - tags
    - master
    - CI

param_XSScan:
  extends: .IStep2
  needs:
    - job: hhCompile
    - job: LHProcess
  variables:
    output_dir: output/param
    mini_option: minimizer_fixXSunc.json
    np_option: np_map_kl_v10.json
    other_options: "--file_format <mass[F]>_kl --param klambda=-2_6_1"
  allow_failure: true
  script:
    - echo HHComb combine_ws -i $output_dir -r nonres -c bbyy,bbtautau --minimizer_options configs/${mini_option} --scheme configs/${np_option} $other_options
    - HHComb combine_ws -i $output_dir -r nonres -c bbyy,bbtautau --minimizer_options configs/${mini_option} --scheme configs/${np_option} $other_options
  only:
    - tags
    - master
    - CI

###################################
## Plotting                      ##
###################################
.plot:
  stage: plotting
  variables:
    GIT_SSL_NO_VERIFY: "true"
    configuration: project3000
  before_script:
    - set +e
    - shopt -s expand_aliases
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
    - source setup.sh || echo ignore setupATLAS return code
  allow_failure: true
  only:
    - tags
    - master
    - CI

NRPlot:
  extends: .plot
  needs:
    - job: NR_proj_comb_mu
    - job: NR_proj_comb_stat
  variables:
    input_stat_dir: output/stat
    input_dir: output/NR
  script:
    # Plot nonres signal strength (mu)
    - echo python plotting/xsection/combination_plotting.py nonres --logx -l $input_dir/limits/nonres/*/0.json $input_dir/limits/nonres/combined/A-*-fullcorr/0.json -s $input_stat_dir/limits/nonres/bb[ty]*/0.json $input_stat_dir/limits/nonres/combined/A-*-fullcorr/0.json -mu --config ${configuration} --norm 1000
    - python plotting/xsection/combination_plotting.py nonres --logx -l $input_dir/limits/nonres/*/0.json $input_dir/limits/nonres/combined/A-*-fullcorr/0.json -s $input_stat_dir/limits/nonres/bb[ty]*/0.json $input_stat_dir/limits/nonres/combined/A-*-fullcorr/0.json -mu --config ${configuration} --norm 1000
  artifacts:
    paths:
      - $input_dir/figures

KLPlot:
  extends: .plot
  needs:
    - job: KL_proj_pro_yy
    - job: KL_proj_pro_tt
    - job: indiv_XSScan
    - job: param_XSScan
  variables:
    input_dir_indiv: output/indiv/
    input_dir_param: output/param/
  script:
    # Plot KL
    - echo python plotting/kl_scan/plot_kl.py -i $input_dir_param -ci --config ${configuration}
    - python plotting/kl_scan/plot_kl.py -i $input_dir_param -ci --config ${configuration}
    - echo python plotting/kl_scan/plot_kl.py -i $input_dir_indiv -ci --config ${configuration}
    - python plotting/kl_scan/plot_kl.py -i $input_dir_indiv -ci --config ${configuration}
  artifacts:
    paths:
      - $input_dir_param/figures
      - $input_dir_indiv/figures

LHPlot:
  extends: .plot
  needs:
    - job: param_LHScan
  variables:
    input_dir_param: output/param/
  script:
    # Plot kl likelihood curve
    - echo python plotting/likelihood/likelihood_plotting.py -a nonres -i $input_dir_param/likelihood/kl1 -c combined_klambda.json -t bbtautau_klambda.json -y bbyy_klambda.json -o $input_dir_param/figures/ --threshold 12
    - python plotting/likelihood/likelihood_plotting.py -a nonres -i $input_dir_param/likelihood/kl1 -c combined_klambda.json -t bbtautau_klambda.json -y bbyy_klambda.json -o $input_dir_param/figures/ --threshold 12

  artifacts:
    paths:
      - $input_dir_param/figures


#####################################
## Intermediate output to download ##
#####################################
Artifacts:
  stage: download
  variables:
    GIT_SSL_NO_VERIFY: "true"
    output: output
  allow_failure: true
  script:
    - ls
  only:
    - tags
    - master
    - CI
  artifacts:
    paths:
      - $output
