dataset:
  bbtautau:
    blind: asimovData
    unblind: obsData
  bbyy:
    blind: combData
    unblind: combData
  combination:
    blind: combData
    unblind: combData
poi:
  bbtautau: SigXsecOverSM
  bbyy: mu_XS_HH
  combination: xsec_br
rescale_poi:
  bbtautau: 1.0
  bbyy: 1.0