dataset:
  bbtautau:
    blind: asimovData
  bbyy:
    blind: combData
  combination:
    blind: combData
poi:
  bbtautau: mu
  bbyy: mu_XS_HH
  combination: xsec_br
rescale_poi:
  #kl no rescaling needed
  bbyy: 1
  bbtautau: 1
likelihood_scan:
  klambda_1:
    generate_asimov: -2
    dataset: asimovData_1_NP_Nominal
    poi_name: klambda
    fix: xsec_br=1
    min : -10
    max : 10
    step: 0.1