dataset:
  bbbb:
    blind: obsData
    unblind: obsData
  bbtautau:
    blind: obsData
    unblind: obsData
  bbyy:
    blind: combData
    unblind: combData
  bbll:
    blind: obsData
    unblind: obsData
  bbVV:
    blind: obsData
    unblind: obsData
  WWWW:
    blind: asimovData
    unblind: asimovData
  combination:
    blind: combData
    unblind: combData
poi:
  bbbb: mu
  bbtautau: SigXsecOverSM
  bbyy: mu_XS_HH
  bbll: mu_SIG
  bbVV: SigXsecOverSM
  WWWW: SigXsecOverSM
  combination: xsec_br
rescale_poi:
  bbyy: 0.032743
  # changed to 32.776 (32.743) since HH NF are ready
  #(32.776/1)*(5.824/5.809)*(6.272/6.256) = 32.944677
  bbtautau: 32.743
redefine_parameters:
  bbtautau:
    # to be implemented once HH NF are ready
    #ATLAS_norm_hhttbb: (6.256/6.272)*(5.809/5.824) * 31.02/31.05 = 0.99391876
    #ATLAS_norm_hhttbbVBF: (6.256/6.272)*(5.809/5.824) * 1.723/1.726 = 0.99315078
    ATLAS_norm_hhttbb: 0.99391876
    ATLAS_norm_hhttbbVBF: 0.99315078

    #ATLAS_norm_VBFHtautau: 1/1.0012985 * 0.99744898 = 0.99615547
    #ATLAS_norm_ggFHtautau: 1/1.0007939 * 0.99744898 = 0.99665773
    ATLAS_norm_VBFHtautau: 0.99615547
    ATLAS_norm_ggFHtautau: 0.99665773
    # these are single H XS Htautau br (6.256/6.272 = 0.99744898) or Hbb br (5.809/5.824 = 0.99742445)
    # https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageAt13TeV#ppZH_Total_Cross_Section_with_ap
    #        ZH      ggZH    qqZH
    #125.00  0.8839  0.1227  0.7612
    #125.09  0.8824  0.1227  0.7597
    #ATLAS_norm_qqZHbb: (0.7597/0.7612) * 0.99742445 = 0.99545895
    #ATLAS_norm_ggZHbb: (1. * 0.99742445)
    #ATLAS_norm_ttH: 1/1.0011846 * 0.99744898 = 0.99626880
    #ATLAS_norm_WHbb: 1/1.0025569 * 0.99742445 = 0.99488064
    #ATLAS_norm_qqZHtautau: (0.7597/0.7612) * 0.99744898 = 0.99548343
    #ATLAS_norm_ggZHtautau: 1. * 0.99744898
    #ATLAS_norm_WHtautau: 1/1.0025569 * 0.99744898 = 0.99490511
    ATLAS_norm_qqZHbb: 0.99545895
    ATLAS_norm_ggZHbb: 0.99742445
    ATLAS_norm_ttH: 0.99626880
    ATLAS_norm_WHbb: 0.99488064
    ATLAS_norm_qqZHtautau: 0.99548343
    ATLAS_norm_ggZHtautau: 0.99744898
    ATLAS_norm_WHtautau: 0.99490511
