Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/stat_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/stat_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/theo_exp_baseline/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/theo_exp_baseline/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/theo_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/theo_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/run2_syst/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1000ifb/run2_syst/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/stat_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/stat_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/theo_exp_baseline/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/theo_exp_baseline/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/theo_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/theo_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/run2_syst/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi1500ifb/run2_syst/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/stat_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/stat_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/theo_exp_baseline/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/theo_exp_baseline/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/theo_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/theo_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/run2_syst/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2000ifb/run2_syst/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/stat_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/stat_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/theo_exp_baseline/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/theo_exp_baseline/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/theo_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/theo_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/run2_syst/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi2500ifb/run2_syst/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/stat_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/stat_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/stat_only/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/stat_only/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.1____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_stat_only.json____--do-limit____--do-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_exp_baseline/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_exp_baseline/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_exp_baseline/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty_no_kl_unc.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_exp_baseline/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.1____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty_no_kl_unc.json____--do-limit____--do-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_only/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_only/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_only/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/theo_only/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.1____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--do-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/run2_syst/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/run2_syst/SM_xsec____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/run2_syst/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/run2_syst/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.1____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_fix_xs_uncertainty.json____--do-limit____--do-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/tutorials/projection2022/output/20221018_proj_all/lumi3000ifb/optimistic/SM_mu____-s____${hh_combination_fw_path}/configs/correlation_schemes/projection2022/nonres_kl_v14.json____-c____bbyy,bbtautau,bbbb____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/projection2022/proj_nonres_sm.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection2021/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
