Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1000ifb/stat_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1000ifb/theo_exp_baseline/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1000ifb/theo_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1000ifb/run2_syst/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1500ifb/stat_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1500ifb/theo_exp_baseline/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1500ifb/theo_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi1500ifb/run2_syst/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2000ifb/stat_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2000ifb/theo_exp_baseline/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2000ifb/theo_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2000ifb/run2_syst/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2500ifb/stat_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2500ifb/theo_exp_baseline/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2500ifb/theo_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi2500ifb/run2_syst/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/stat_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_stat_only.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/stat_only/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_stat_only.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/stat_only/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.2____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_stat_only.json____--do-limit____--do-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/theo_exp_baseline/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_no_kl_unc.json____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/theo_exp_baseline/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_fix_xs_uncertainty_no_kl_unc.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/theo_exp_baseline/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.2____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_fix_xs_uncertainty_no_kl_unc.json____--do-limit____--do-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/theo_only/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/theo_only/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/theo_only/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.2____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_fix_xs_uncertainty.json____--do-limit____--do-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/run2_syst/SM____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--do-limit____--skip-likelihood____--do-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/run2_syst/kl_individual____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl_<klambda[P]>____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_v11.yaml____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_fix_xs_uncertainty.json____--do-limit____--skip-likelihood____--skip-pvalue
Queue 1
Arguments = HHComb____combine_ws____-i____${hh_combination_fw_path}/output/projection_nonres_14TeV_3000ifb/lumi3000ifb/run2_syst/kl_parameterised____-s____${hh_combination_fw_path}/configs/correlation_schemes/nonres_kl_v10.json____-c____bbyy,bbtautau____-r____nonres____--file_expr____<mass[F]>_kl____--config____${hh_combination_fw_path}/configs/task_options/proj_nonres_kl.yaml____--param_expr____klambda=-2_8_0.2____--minimizer_options____${hh_combination_fw_path}/configs/minimizer_options/projection_fix_xs_uncertainty.json____--do-limit____--do-likelihood____--skip-pvalue
Queue 1
