dataset:
  bbbb:
    blind: obsData
    unblind: obsData
  bbtautau:
    blind: obsData
    unblind: obsData
  bbyy:
    blind: combData
    unblind: combData
  bbll:
    blind: obsData
    unblind: obsData
  bbVV:
    blind: obsData
    unblind: obsData
  WWWW:
    blind: asimovData
    unblind: asimovData
  combination:
    blind: combData
    unblind: combData
poi:
  bbbb: mu
  bbtautau: SigXsecOverSM
  bbyy: mu_XS_HH
  bbll: mu_SIG
  bbVV: SigXsecOverSM
  WWWW: SigXsecOverSM
  combination: xsec_br
redefine_parameters:
  bbyy:
    mu_XS_H: 1.0010078490058945
    mHNom_SM_1: 125
    mHNom_SM_2: 125
    mHNom_BSM_1: 125
    mHNom_BSM_2: 125