dataset:
  bbtautau:
    blind: obsData
  bbyy:
    blind: combData
  combination:
    blind: combData
poi:
  bbtautau: klambda
  bbyy: klambda
  combination: klambda

rescale_poi:
  #kl no rescaling needed
  bbtautau: 1
  bbyy: 1
