dataset:
  bbbb:
    blind: obsData
    unblind: obsData
  bbtautau:
    blind: obsData
    unblind: obsData
  bbyy:
    blind: combData
  WWWW:
    blind: asimovData
  combination:
    blind: combData
    unblind: combData
poi:
  bbbb: mu
  bbtautau: SigXsecOverSM
  bbyy: mu_XS_HH
  WWWW: SigXsecOverSM
  combination: xsec_br
