dataset:
  bbbb:
    blind: obsData
    unblind: obsData
  bbtautau:
    blind: obsData
    unblind: obsData
  bbyy:
    blind: combData
    unblind: combData
  WWWW:
    blind: asimovData
  combination:
    blind: combData
    unblind: combData
poi:
  bbbb: xsec_br
  bbtautau: SigXsecOverSM
  bbyy: XS_HH_res
  WWWW: SigXsecOverSM
  combination: xsec_br
