workspace:
  bbtautau: combined
  bbbb: combined
  bbyy: combWS

dataset:
  bbbb:
    blind: obsData
    unblind: obsData
  bbtautau:
    blind: obsData
    unblind: obsData
  bbyy:
    blind: combData
    unblind: combData
  combination:
    blind: combData
    unblind: combData
poi:
  bbbb: mu_HH
  bbtautau: mu
  bbyy: mu
  combination: xsec_br
rescale_poi:
  #kl no rescaling needed
  bbbb: 1
  bbyy: 1
  bbtautau: 1

extra_pois:
  bbbb:
    - kt
    - klambda
    - k2V
    - kF
    - kH
    - kV
    - kW
    - kZ
    - kb
    - ktau
    - mu_HH_VBF
    - mu_HH_ggF
  bbtautau:
    - kt
    - klambda
    - kF
    - kH
    - kV
    - kW
    - kZ
    - kb
    - ktau
  bbyy:
    - kt
    - klambda
    - k2V
    - kF
    - kH
    - kV
    - kW
    - kZ
    - kb
    - ktau
    - mu_VBFHH
    - mu_ggFHH
