dataset:
  bbbb:
    blind: obsData
    unblind: obsData
  bbtautau:
    blind: obsData
    unblind: obsData
  bbyy:
    blind: combData
    unblind: combData
  combination:
    blind: combData
    unblind: combData

poi:
  bbbb: mu_HH
  bbtautau: SigXsecOverSM # Note different names than 0_kl.root which is mu
  bbyy: mu_XS_HH # Note different names than 0_kl.root which is mu
  combination: xsec_br

rescale_poi:
  #kl no rescaling needed
  bbbb: 1
  bbyy: 1
  bbtautau: 1

redefine_parameters:
  bbbb:
    - mu_HH_VBF[1,-10000,10000]
    - mu_HH_ggF[1,-10000,10000]

# fix POIs so that they are set to const
fix_parameters:
  bbyy: <pois>
  bbtautau: <pois>
  bbbb: <pois>,xsec_br=1_-10000_10000
  combination: <pois>

## Check if POIs are floated in the input workspace
## If so, include all POIs here so that process_channel will fix all POI to const
## This is important if input WS contains multiple POIs
extra_pois:
  bbbb:
    - k2V
    - kV
    - klambda
    - mu_HH_VBF
    - mu_HH_ggF
  bbtautau:
  bbyy:
  combination:
