workspace:
  bbtautau: combined
  bbbb: combined
  bbyy: combWS

dataset:
  bbbb:
    blind: obsData
    unblind: obsData
  bbtautau:
    blind: obsData
    unblind: obsData
  bbyy:
    blind: combData
    unblind: combData
  combination:
    blind: combData
    unblind: combData
poi:
  bbbb: mu_HH
  bbtautau: mu
  bbyy: mu
  combination: xsec_br
rescale_poi:
  #kl no rescaling needed
  bbbb: 1
  bbyy: 1
  bbtautau: 1

# redefine POIs so that they are set to const
#redefine_parameters:

# add k2V to bbtautau while waiting for their VBF parametrisation
define_parameters:
  bbtautau:
    - k2V[1]

extra_pois:
  bbbb:
    - kt
    - klambda
    - k2V
    - kF
    - kH
    - kV
    - kW
    - kZ
    - kb
    - ktau
    - mu_HH_VBF
    - mu_HH_ggF
  bbtautau:
    - kt
    - klambda
    - k2V
    - kF
    - kH
    - kV
    - kW
    - kZ
    - kb
    - ktau
  bbyy:
    - kt
    - klambda
    - k2V
    - kF
    - kH
    - kV
    - kW
    - kZ
    - kb
    - ktau
    - mu_HH_VBF
    - mu_HH_ggF
  combination:
    - kt
    - klambda
    - k2V
    - kF
    - kH
    - kV
    - kW
    - kZ
    - kb
    - ktau
    - mu_HH_VBF
    - mu_HH_ggF
rename_parameters:
  bbyy:
    mu_VBFHH: mu_HH_VBF
    mu_ggFHH: mu_HH_ggF
