workspace:
  bbll: w
  bbbb: combined
  bbtautau: combined
  bbyy: combWS
  ml: combWS

dataset:
  bbll:
    blind: asimovData_1_NP_Nominal
    unblind: obsData
  bbbb:
    blind: asimovData_1_NP_Nominal
    unblind: obsData
  bbtautau:
    blind: asimovData_1_NP_Nominal
    unblind: obsData
  bbyy:
    blind: asimovData_1_NP_Nominal
    unblind: combData
  ml:
    blind: asimovData_1_NP_Nominal
    unblind: obsData
  combination:
    blind: asimovData_1_NP_Nominal
    unblind: combData

poi:
  bbll: mu_SIG
  bbbb: mu_HH
  bbtautau: SigXsecOverSM
  bbyy: mu_HH
  ml: mu_XS_hh
  combination: xsec_br

fix_parameters:
  bbll: <poi>
  bbbb: <poi>
  bbtautau: <poi>
  bbyy: <poi>
  ml: <poi>
  combination: <poi>

extra_pois:
  bbll:
  bbbb: k2V,kV,klambda,kt,mu_HH_VBF,mu_HH_ggF
  bbtautau:
  bbyy: mu_H,mu_HH_VBF,mu_HH_ggF,mu_HM_1,mu_HM_2,mu_HM_3,mu_H_HH,mu_LM_1,mu_LM_2,mu_LM_3,mu_LM_4,mu_VBFH,mu_WmH,mu_WpH,mu_ZH,mu_bbH,mu_ggH,mu_ggZH,mu_tHjb,mu_tWH,mu_ttH
  ml:

set_parameters:
  bbll: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  bbbb: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  bbtautau: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  bbyy: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  ml: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1

tasks:
  limit:
    - scenario: nominal
      channels:
        - bbll
        - bbbb
        - bbtautau
        - bbyy
        - ml
        - combination
      options:
        fix_param: "gamma_saturated_model*=1"
    - scenario: xsec
      channels:
        - bbll
        - bbbb
        - bbtautau
        - bbyy
        - ml
        - combination
      options:
        fix_param: "gamma_saturated_model*=1,*THEO_XS_COMBINED*=0,*THEO_XS_PDF*HH=0,*HH_PDF*=0,*HH_Alphas=0,*HH_Scale=0,*THEO_XS_*SCALE*HH=0,*THEO_XS_*ggf=0,*THEO_XS_*vbf=0,*THEO_*_SIG=0"
