workspace:
  bbll: combined
  bbbb: combined
  bbyy: combWS
  bbtautau: combined
  # ml: combined

dataset:
  bbll:
    blind: asimovData_muhat_NP_Profile
    unblind: combData
  bbbb:
    blind: asimovData_muhat_NP_Profile
    unblind: obsData
  bbyy:
    blind: asimovData_muhat_NP_Profile
    unblind: combData
  bbtautau:
    blind: asimovData_muhat_NP_Profile
    unblind: combData
  # ml:
  #   blind: asimovData_muhat_NP_Profile
  #   unblind: obsData
  combination:
    blind: asimovData_muhat_NP_Profile
    unblind: combData

poi:
  bbll: mu_HH
  bbbb: mu
  bbyy: mu_HH
  bbtautau: mu
  # ml: mu_XS_hh
  combination: mu

fix_parameters:
  bbll: <poi>=1
  bbbb: <poi>=1
  bbyy: <poi>=1
  bbtautau: <poi>=1
  # ml: <poi>=1
  combination: <poi>=1

gen_asimov:
  bbll: 2,-2
  bbbb: 2,-2
  bbyy: 2,-2
  bbtautau: 2,-2
  # ml: 2,-2
  combination: 2,-2

add_syst:
  bbll: mu_ZHF_VBF_HH,mu_ZHF_vetoVBF_HH,mu_singletop_VBF_HH,mu_singletop_vetoVBF_HH,mu_ttbar_VBF_HH,mu_ttbar_vetoVBF_HH

rename_parameters:
  bbll:
    kappaL: kl
    kappa2V: k2v
  bbbb:
    kLambda: kl
    k2V: k2v
  bbyy:
    mu_HH_ggF: mu_ggF
    mu_HH_VBF: mu_VBF
  bbtautau:
    kappaL: kl
    kappa2V: k2v
    mu_GGF: mu_ggF

extra_pois:
  bbll: kl,k2v,mu_ggF,mu_VBF
  bbbb: kl,k2v,mu_ggF,mu_VBF,kV,kt
  bbyy: kl,k2v,mu_ggF,mu_VBF,kv,mu_H,mu_HM_1,mu_HM_2,mu_HM_3,mu_H_HH,mu_LM_1,mu_LM_2,mu_LM_3,mu_LM_4,mu_VBFH,mu_WmH,mu_WpH,mu_ZH,mu_bbH,mu_ggH,mu_ggZH,mu_tHjb,mu_tWH,mu_ttH
  bbtautau: kl,k2v,mu_ggF,mu_VBF,mu_VBFHtautau,mu_WHbb,mu_WHtautau,mu_ggFHtautau,mu_ggZHbb,mu_ggZHtautau,mu_qqZHbb,mu_qqZHtautau,mu_ttH
  # ml: 
  combination: kl,k2v,mu_ggF,mu_VBF

set_parameters:
  bbll: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  bbbb: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  bbyy: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  bbtautau: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1
  # ml: <GAUSSIAN_CONSTRAINT_NP>=0,<POISSON_CONSTRAINT_NP>=1

tasks:
  limit:
    - scenario: mu_VBF
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        poi_name: mu_VBF
        eps: 0.1
        fix_param: "alpha_ATLAS_KLAMBDA_REWEIGHTING_HH_ggF_HH,alpha_ATLAS_LC_CLOSURE_VBFSMHH_HH,alpha_ATLAS_HEFT_REWEIGHTING_HH_ggF_HH,alpha_SysSIGNAL_KLRW_STAT_HH,ATLAS_GGF_Parametrization,ATLAS_VBF_Parametrization,ATLAS_ggF_Parametrization,HEFT_HHReW_systUncert,alpha_THEO_KAPPA_LAMBDA_HH,ATLAS_KAPPA_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_HH_VBF,ATLAS_HEFT_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_STAT_HH"
    - scenario: mu_ggF
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        poi_name: mu_ggF
        eps: 0.1
        fix_param: "alpha_ATLAS_KLAMBDA_REWEIGHTING_HH_ggF_HH,alpha_ATLAS_LC_CLOSURE_VBFSMHH_HH,alpha_ATLAS_HEFT_REWEIGHTING_HH_ggF_HH,alpha_SysSIGNAL_KLRW_STAT_HH,ATLAS_GGF_Parametrization,ATLAS_VBF_Parametrization,ATLAS_ggF_Parametrization,HEFT_HHReW_systUncert,alpha_THEO_KAPPA_LAMBDA_HH,ATLAS_KAPPA_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_HH_VBF,ATLAS_HEFT_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_STAT_HH"
    - scenario: xsec_kl # kl scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        poi_name: mu
        eps: 0.1
        fix_param: "alpha_PDFaSXS_ggF,alpha_THEO_XS_PDFalphas_ggf,alpha_ScalemtopXS_ggF,alpha_THEO_XS_SCALEMTop_ggf,alpha_SysTHEO_XS_PDFalphas_ggFSMHH_HH,alpha_SysTHEO_XS_SCALEMTop_ggFSMHH_HH,THEO_XS_COMBINED_ggFHH,THEO_XS_PDF_alphaS_ggFHH,alpha_THEO_PDFALPHAS_SIG,alpha_THEO_SCALEMTOP_SIG,alpha_THEO_PDFALPHAS_SIG_HH,alpha_THEO_SCALEMTOP_SIG_HH,alpha_THEO_XS_ggFHH_PDFAlphas,alpha_THEO_XS_ggFHH_SCALEMTop,THEO_XS_ggFHH_SCALEMTop,THEO_XS_ggFHH_PDFalphaS,alpha_PDFaSXS_VBF,alpha_THEO_XS_SCALEMTop_vbf,alpha_SysTHEO_XS_PDFalphas_VBFSMHH_HH,THEO_XS_PDF_alphaS_VBFHH,THEO_XS_QCD_SCALE_VBFHH,alpha_THEO_PDFALPHAS_SIGVBF_HH,alpha_THEO_XS_VBFHH_PDFAlphas,THEO_XS_VBFHH_PDFalphaS,THEO_XS_VBFHH_SCALEMTop"
        param_expr: kl=-10_20_0.1
    - scenario: xsec_k2v # k2v scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        poi_name: mu_VBF
        eps: 0.1
        fix_param: "alpha_PDFaSXS_VBF,alpha_THEO_XS_SCALEMTop_vbf,alpha_SysTHEO_XS_PDFalphas_VBFSMHH_HH,THEO_XS_PDF_alphaS_VBFHH,THEO_XS_QCD_SCALE_VBFHH,alpha_THEO_PDFALPHAS_SIGVBF_HH,alpha_THEO_XS_VBFHH_PDFAlphas,THEO_XS_VBFHH_PDFalphaS,THEO_XS_VBFHH_SCALEMTop"
        param_expr: k2v=-3_6_0.1
  likelihood:
    - scenario: kl_obs # 1d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        param_expr: kl=-10_20_0.1
    - scenario: kl_exp # 1d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        param_expr: kl=-10_20_0.1
        data_name: asimovData_muhat_NP_Profile
        snapshot_name: asimovData_muhat_NP_Profile
    - scenario: k2v_obs # 1d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        param_expr: k2v=-3_6_0.1
    - scenario: k2v_exp # 1d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        param_expr: k2v=-3_6_0.1
        data_name: asimovData_muhat_NP_Profile
        snapshot_name: asimovData_muhat_NP_Profile
    - scenario: kl_k2v_obs # 2d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        param_expr: kl=-10_20_1,k2v=-3_6_0.3
    - scenario: kl_k2v_exp # 2d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        param_expr: kl=-10_20_1,k2v=-3_6_0.3
        data_name: asimovData_muhat_NP_Profile
        snapshot_name: asimovData_muhat_NP_Profile
    - scenario: muVBF_muggF_obs # 2d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        fix_param: mu_VBF=1_-100_160,mu_ggF=1_-10_16
        param_expr: mu_ggF=-10_16_1,mu_VBF=-100_160_10
        fix_param: "alpha_ATLAS_KLAMBDA_REWEIGHTING_HH_ggF_HH,alpha_ATLAS_LC_CLOSURE_VBFSMHH_HH,alpha_ATLAS_HEFT_REWEIGHTING_HH_ggF_HH,alpha_SysSIGNAL_KLRW_STAT_HH,ATLAS_GGF_Parametrization,ATLAS_VBF_Parametrization,ATLAS_ggF_Parametrization,HEFT_HHReW_systUncert,alpha_THEO_KAPPA_LAMBDA_HH,ATLAS_KAPPA_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_HH_VBF,ATLAS_HEFT_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_STAT_HH"
    - scenario: muVBF_muggF_exp # 2d scan
      channels:
        - bbll
        - bbbb
        - bbyy
        - bbtautau
        - combination
      options:
        eps: 0.1
        fix_param: mu_VBF=1_-100_160,mu_ggF=1_-10_16
        param_expr: mu_ggF=-10_16_1,mu_VBF=-100_160_10
        data_name: asimovData_muhat_NP_Profile
        snapshot_name: asimovData_muhat_NP_Profile
        fix_param: "alpha_ATLAS_KLAMBDA_REWEIGHTING_HH_ggF_HH,alpha_ATLAS_LC_CLOSURE_VBFSMHH_HH,alpha_ATLAS_HEFT_REWEIGHTING_HH_ggF_HH,alpha_SysSIGNAL_KLRW_STAT_HH,ATLAS_GGF_Parametrization,ATLAS_VBF_Parametrization,ATLAS_ggF_Parametrization,HEFT_HHReW_systUncert,alpha_THEO_KAPPA_LAMBDA_HH,ATLAS_KAPPA_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_HH_VBF,ATLAS_HEFT_REWEIGHTING_HH_ggF,ATLAS_KAPPA_REWEIGHTING_STAT_HH"