workspace:
  bbtautau: combined
  bbyy: combWS
dataset:
  bbtautau:
    blind: asimovData
  bbyy:
    blind: combData
  combination:
    blind: combData
poi:
  bbtautau: mu
  bbyy: mu_XS_HH
  combination: xsec_br
rescale_poi:
  #kl no rescaling needed
  bbyy: 1
  bbtautau: 1
likelihood_scan:
  klambda_0:
    # generate prefit asimov dataset at kl = 0, xsec_br = 1
    generate_asimov: -1
    dataset: asimovData_0_NP_Nominal
    poi_name: klambda
    # fix kl = 0 to make sure the initial value of kl is 0 (instead of -999) when doing unconditional fit
    fix: xsec_br=1,klambda=0
    min : -10
    max : 10
    step: 0.1
  klambda_1:
    generate_asimov: -2
    dataset: asimovData_1_NP_Nominal
    poi_name: klambda
    # fix kl = 0 to make sure the initial value of kl is 1 (instead of -999) when doing unconditional fit
    fix: xsec_br=1,klambda=1
    min : -10
    max : 10
    step: 0.1
